### ISSUE TITLE
Question de cours n°19

### ISSUE THREAD

**Issue by BehagueQuentin** [bongibault-romain/informatique#1]
Salut Romain,
Tout d'abord, je voulais te remercier de partager ce document, et je me permet de te laisser un message pour te dire que dans la dernière ligne de la fonction tri_rap, il serait plus efficace d'écrire :
    | a::suite -> let l1,l2 = pivot a suite in (tri_rap l1)@(a::(tri_rap l2))
Au lieu de : 
    | a::suite -> let l1,l2 = pivot a suite in (tri_rap l1)@[a]@(tri_rap l2)
Car l'opération de concaténation @ est plus coûteuse en temps.
Je me trompe peut-être…
Bonne soirée
Quentin

**Comment by bongibault-romain** [comment]
Je le corrigerai
